### ISSUE TITLE
[Testlauf beenden] mit Button Ergebnisse abschicken

### ISSUE THREAD

**Issue by ksch10bob** [datatrain/automatedChangelog#14]
#### Beschreibung

nachdem alle Tests durchgeführt worden sind  erscheint ddie View mit einem Button "Ergebnisse abschicken" den man beliebig oft anklicken kann und dadurch ein neuer zum Testlauf zugeordneter  Milestone angelegt wird.
Es wäre aber sinnvoll nach erfolgreichem anlegen eines Milestones den Button zu deaktivieren bzw. die View zu wechseln.

#### Reproduzieren
* einen Testlauf starten
* alle Tests durchführen oder überspringen
* auf "Ergebnisse sichern" klicken 

#### Erwartetes Ergebnis

Der Button wird inaktiv und eine Meldung "Die Ergebnisse des Testlaufs wurden erfolgreich gesichert" erscheint

#### Resultat

nichts von beiden passiert, man kann also beliebig viele Milestones nach Beenden eines Testlaufs anlegen

**Comment by orummel** [comment]
Gefixt ab v0.9.0

Meldungen sind noch nicht implementiert und sollten in einem gesonderten Issue behandelt werden

**Comment by ksch10bob** [comment]
tested und zwar erfolgreich
