### ISSUE TITLE
[Fehlerhafter Testdurchlauf] durch Seitenwechsel

### ISSUE THREAD

**Issue by ksch10bob** [datatrain/automatedChangelog#20]
#### Beschreibung
navigiert man während eines Testlaufs aus der Test View und danach zurück, befindet sich die View zwar noch auf dem Stand vor dem Verlassen, doch wenn mann nun den aktuellen Test beendet, startet der Test von neuem

#### Reproduzieren

* eine nicht leere Testsuite aus einem Projekt wählen  
*  Testlauf sarten und erste Schritte der ersten Tests durchführen
*  vor dem Beenden des Testlaufs mit der Browserfunktion zurück navigieren und sofort wieder 
 nach vorn navigieren 

#### Erwartetes Ergebnis 

der Testlauf kann an dem Punkt weitergeführt werden, an dem die Seite verlassen wurde

#### Resultat

Der Testlauf kann zwar fortgeführt werden nur beginnt er nach beenden des letzten aktuellen Tests im Testdurchlauf wieder mit dem ersten Test des Testdurchlaufs

**Comment by orummel** [comment]
Gefixt ab v0.9.1

**Comment by ksch10bob** [comment]
erfolgreich getestet auf chrome
