### ISSUE TITLE
[Testrun bei Failed Testcase] Testrun bricht nach erstem failed Test ab

### ISSUE THREAD

**Issue by ksch10bob** [datatrain/automatedChangelog#25]
#### Beschreibung

Ein testrun mit mehreren Test wird beendet, wenn irgendein Test des Testruns fehlschlägt

#### Reproduzieren
* Testlauf mit mind. zwei Testfällen starten
* während des nicht letzten Testfalls auf den "unerwartetes Verhalten" Button klicken
* Bemerkung eingeben und Button "Testfall gescheitert" klicken
 

#### Erwartetes Ergebnis

Der Testrun fährt mit dem nächsten Test fort

#### Aktuelles Ergebnis

Der Testrun wird als komplett angezeigt und man hat nur noch die Möglichkeit die Ergebnisse abzuschicken oder zu verwerfen

**Comment by orummel** [comment]
Verfügbar ab v0.9.25

**Comment by ksch10bob** [comment]
erfolgreich getestet auf chrome
